{{config(
  materialized='table',
  alias='ORDERS_HAVING_PROFIT_TBL',
  post_hook=[
    "CREATE OR REPLACE TABLE TRANSFORMATION_DB.RAW_SCH.PUBLIC_ORDERS_DATA_TBL AS 
     SELECT CUSTOMERID,PRODUCTID,ORDERSELLINGPRICE FROM {{this}};"
  ]
)
}}

SELECT * FROM {{ source('RAW_DATA','RAW_ORDERS')}}
WHERE ORDERSELLINGPRICE > ORDERCOSTPRICE